version: 0.2

phases:
  build:
    commands:
      - echo Ejecutar comando de validate-template
      - cd ~/environment/bootcamp-module-devops/
      - aws cloudformation validate-template --template-body file://talleres/07/api-cfn-pipeline.yaml 

artifacts:
  # Archivos a exportar
  files:
    - talleres/07/api-cfn-pipeline.yaml
  discard-paths: yes
